api_platform:
  title: "Hop REST API"
  description: "Hop API to manage a simple  app."
  version: "1.0.0"
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header